name: Run Qase Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt || true  # In case requirements.txt is missing
          pip install requests python-dotenv

      - name: Run Qase test script
        env:
          QASE_API_TOKEN: ${{ secrets.QASE_API_TOKEN }}
        run: |
          source venv/bin/activate
          python qase_tester.py
